<?php 

return [
    'code' => 'MX',
    'name' => 'Mexico',
    'states' => collect([
        'AG' => 'Aguascalientes',
        'BC' => 'Baja California',
        'BS' => 'Baja California Sur',
        'CM' => 'Campeche',
        'CS' => 'Chiapas',
        'CH' => 'Chihuahua',
        'CX' => 'Ciudad de México (Distrito Federal)',
        'CO' => 'Coahuila',
        'CL' => 'Colima',
        'DG' => 'Durango',
        'EM' => 'Estado de México',
        'GT' => 'Guanajuato',
        'GR' => 'Guerrero',
        'HG' => 'Hidalgo',
        'JC' => 'Jalisco',
        'MI' => 'Michoacan',
        'MO' => 'Morelos',
        'NA' => 'Nayarit',
        'NL' => 'Nuevo León',
        'OA' => 'Oaxaca',
        'PU' => 'Puebla',
        'QT' => 'Querétaro',
        'QR' => 'Quintana Roo',
        'SL' => 'San Luis Potosí',
        'SI' => 'Sinaloa',
        'SO' => 'Sonora',
        'TB' => 'Tabasco',
        'TM' => 'Tamaulipas',
        'TL' => 'Tlaxcala',
        'VE' => 'Veracruz',
        'YU' => 'Yucatán',
        'ZA' => 'Zacatecas',
    ]),
];